Update padavan-4.4-build.yml

diff --git a/.github/workflows/padavan-4.4-build.yml b/.github/workflows/padavan-4.4-build.yml
--- a/.github/workflows/padavan-4.4-build.yml
+++ b/.github/workflows/padavan-4.4-build.yml
@@ -21,28 +21,39 @@ jobs:
       - uses: actions/setup-go@v3
         with:
           go-version: '1.19.13'
-      - uses: actions/cache@v3
-        with:
-          path: |
-            ~/.cache/go-build
-            ~/go/pkg/mod
-          key: ${{ runner.os }}-go-v1
-          restore-keys: |
-            ${{ runner.os }}-go-
+          cache: false
       - name: Prepare
         run: |
           sudo apt update
           sudo apt -y install libtool-bin gperf python3-docutils autopoint gettext ccache
-          # https://github.com/actions/setup-go/issues/107
-          echo "${GOROOT}/bin" >> $GITHUB_PATH
+
+          export GOROOT=/opt/hostedtoolcache/go/1.19.13/x64
+          export PATH="$GOROOT/bin:$PATH"
+
+          echo "$GOROOT/bin" >> $GITHUB_PATH
+
+          echo "===== GO VERSION ====="
+          which go
+          go version
+          go env GOROOT
+          go env GOPATH
+
       - name: Build
         run: |
+          export GOROOT=/opt/hostedtoolcache/go/1.19.13/x64
+          export PATH="$GOROOT/bin:$PATH"
+
+          echo "===== BUILD GO VERSION ====="
+          which go
+          go version
+          go env GOROOT
+
           TNAME=${{ matrix.target }}
           echo "TNAME=$TNAME"
           cd trunk
           if [ ! -f configs/templates/$TNAME.config ] ; then
-          echo "configs/templates/$TNAME.config not found "
-          exit 1
+            echo "configs/templates/$TNAME.config not found "
+            exit 1
           fi
           cp -f configs/templates/$TNAME.config .config
           sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
